config/routes.rb
Twilio::Application.routes.draw do
  devise_for :users
root to: 'messages#index'
resources :contacts, :only => [:new, :create, :show, :index]
resources :messages, :only => [:index, :new, :create, :show]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
end	

app/models/message.rb
class Message < ActiveRecord::Base
	before_create :send_sms



private
	def send_sms
		response = RestClient::Request.new(
		:method => :post, 
		:url => 'https://api.twilio.com/2010-04-01/Accounts/AC436b69d9566e0de9ad64f8a4504de14a/Messages.json',
		:user => 'AC436b69d9566e0de9ad64f8a4504de14a',
		:password => '5427a8e5e23caf5269a4e6bc88bf6184', 
		:payload => { :Body => body, 
									:From => from, 
									:To => to }
									).execute
	end
end

app/models/user.rb
require 'devise'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contacts_params)
		if @contact.save
			flash[:notice] = "Contact Saved!"
			redirect_to contacts_path(@contact)
		else
			render 'new'
		end
	end

	def show
		@contact = Contact.find(params[:id])
	end

private
	def contacts_params
		params.require(:contact).permit(:name, :phone, :user_id)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :new]

	def index
		@messages = Message.all
	end

	def new
		@message = Message.new
	end	

	def create
		@message = Message.new(message_params)
		if @message.save
			flash[:notice] = "Your mesage was sent!"
			redirect_to messages_path
		else
			render 'new'
		end
	end

	def show
		@message = Message.find(params[:id])
	end	

private
	def message_params
		params.require(:message).permit(:to, :from, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<h1>All the Contacts</h1>

<% current_user.contacts.each do |contact| %>
<ul>
	<li><%= link_to contact.name, contact_path(contact) %></li>
	<%= contact.phone %>
</ul>
<% end %>

app/views/contacts/new.html.erb
<h1>Add a Contact</h1>

<%= form_for @contact do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.submit %>
<% end %>

app/views/contacts/show.html.erb
<h3><%= @contact.name %></h3>
<p><%= @contact.phone %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twilio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Text Message Sender</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/messages/new">Send a Message</a></li>
      <li><a href="/contacts/new">Add a Contact</a></li>
      <li><a href="/contacts">View Contacts</a></li>

    </ul>
    <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  		<%= link_to 'Edit profile', edit_user_registration_path %> |
  		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			<% else %>
  			<%= link_to "Sign up", new_user_registration_path %> |
  			<%= link_to "Login", new_user_session_path %>
			<% end %>
        </ul>
      </li>
    </ul>
  </div>
</div>
<div class="container">
<%= flash[:notice] %>
<%= yield %>
</div>
</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<% @messages.each do |message| %>
<ul>
	<li><%= link_to message.id, message_path(message) %></li>
</ul>
<% end %>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
	<p>Something went wrong: </p>
	<ul>
	<% @message.errors.full_messages_each do |message| %>
		<li><%= message %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @message do |f| %>
	<%= f.label :to %>
	<%= f.text_field :to %>
	<%= f.label :from %>
	<%= f.text_field :from %>
	<%= f.label :body %>
	<%= f.text_area :body, col:100, row:10 %>
	<%= f.submit %>
<% end %>

app/views/messages/show.html.erb
<h1>Your message Sir or Madame</h1>
<ul>
<li>Sent to: <%= @message.to %></li>
<%= @message.body %>
</ul>
<%= link_to "Back", messages_path %>